// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./resources/js/Components/Button.vue')['default']
    Input: typeof import('./resources/js/Components/Input.vue')['default']
  }
}
