// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IcBaselineAccountCircle: typeof import('~icons/ic/baseline-account-circle')['default']
    TopBar: typeof import('./resources/js/Components/TopBar.vue')['default']
  }
}
