version: '3'
services:
  nginx:
    image: nginx
    build: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/www/html
    links:
      - postgres
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    restart: always
  php-fpm:
    image: bitnami/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - /var/log/php-fpm
      - /var/lib/php/session
      - /var/lib/php/upload
      - /var/lib/php/cache
      - /var/lib/php/tmp
    links:
      - nginx
    depends_on:
      - nginx
    restart: always